version: 0.2

env:
  variables:
    REPOSITORY_URI: "861185453846.dkr.ecr.us-east-1.amazonaws.com/eks-cicd-demo"
    REGION: "us-east-1"
    CLUSTER_NAME: "eks-cicd-demo"

phases:
  pre_build:
    commands:
      - IMAGE_TAG=$(date +%s)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - aws eks get-token --cluster-name $CLUSTER_NAME
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - sed -i "s|<ECR_IMAGE_PLACEHOLDER>|$REPOSITORY_URI:$IMAGE_TAG|g" deployment.yaml
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION
      - kubectl --kubeconfig=/root/.kube/config get nodes
      - kubectl apply -f deployment.yaml

artifacts:
  files:
    - deployment.yaml
